### ISSUE TITLE
[Bug] Impossible to plant raisin grapes

### ISSUE THREAD

**Issue by V4lou** [minetest-mirrors/farming#2]
Hello;

I've found a little bug. When i craft a grape with raisin and a trellis, i can't plant the grape on the floor.

Have you a solution to fix this problem ?

Many thanks, by advance.

My configuration:

Linux Mint 21.2
Minetest 5.7.0

**Comment by V4lou** [comment]
Fixed. I'm dumb. Just plant the empty trellis on the floor and plant on this trelli the raisin.

**Comment by V4lou** [comment]
Fixed. I'm dumb. Just plant the empty trellis on the floor and plant on this trelli the raisin.

**Comment by Niklp09** [comment]
@V4lou Please note, this repo is just a mirror. Please report bugs upstream https://codeberg.org/tenplus1/farming/issues
